CREATE TABLE manufacturing_quality.manufacturing_quality_data (
    Inspection_ID INT PRIMARY KEY,
    Inspection_Date DATE,
    Plant VARCHAR(50),
    Production_Line VARCHAR(50),
    Product VARCHAR(50),
    Shift VARCHAR(20),
    Machine_ID VARCHAR(50),
    Operator_ID VARCHAR(50),
    Batch_ID VARCHAR(50),
    Production_Qty INT,
    Defect_Qty INT,
    Defect_Type VARCHAR(100),
    Downtime_Min INT,
    Cycle_Time_Sec DECIMAL(10,2),
    Temperature_C DECIMAL(10,2),
    Pressure_Bar DECIMAL(10,2),
    Vibration_mm_s DECIMAL(10,2),
    Material_Batch VARCHAR(50),
    Supplier VARCHAR(100),
    Inspection_Status VARCHAR(50),
    Temperature_Flag VARCHAR(20),
    Pressure_Flag VARCHAR(20),
    Vibration_Flag VARCHAR(20)
);